//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace xmlObjectProvider.Objects.ZOEB {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pse.pl/osp")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.pse.pl/osp", IsNullable=false)]
    public partial class Komunikat {
        
        private Naglowek naglowekField;
        
        private tTresc trescField;
        
        /// <remarks/>
        public Naglowek Naglowek {
            get {
                return this.naglowekField;
            }
            set {
                this.naglowekField = value;
            }
        }
        
        /// <remarks/>
        public tTresc Tresc {
            get {
                return this.trescField;
            }
            set {
                this.trescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class Naglowek {
        
        private string kod_komField;
        
        private System.DateTime dataField;
        
        private string kod_obiektuField;
        
        private System.DateTime data_utworzeniaField;
        
        private string wersjaField;
        
        private string idField;
        
        private string ref_idField;
        
        /// <remarks/>
        public string kod_kom {
            get {
                return this.kod_komField;
            }
            set {
                this.kod_komField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string kod_obiektu {
            get {
                return this.kod_obiektuField;
            }
            set {
                this.kod_obiektuField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data_utworzenia {
            get {
                return this.data_utworzeniaField;
            }
            set {
                this.data_utworzeniaField = value;
            }
        }
        
        /// <remarks/>
        public string wersja {
            get {
                return this.wersjaField;
            }
            set {
                this.wersjaField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ref_id {
            get {
                return this.ref_idField;
            }
            set {
                this.ref_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tPasmoPozycjiGrafiku {
        
        private string npField;
        
        private decimal oFPField;
        
        private string oFCGField;
        
        private string oFCDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NP {
            get {
                return this.npField;
            }
            set {
                this.npField = value;
            }
        }
        
        /// <remarks/>
        public decimal OFP {
            get {
                return this.oFPField;
            }
            set {
                this.oFPField = value;
            }
        }
        
        /// <remarks/>
        public string OFCG {
            get {
                return this.oFCGField;
            }
            set {
                this.oFCGField = value;
            }
        }
        
        /// <remarks/>
        public string OFCD {
            get {
                return this.oFCDField;
            }
            set {
                this.oFCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tDaneIloscioweZgloszenia {
        
        private string pField;
        
        private decimal pMAXField;
        
        private bool pMAXFieldSpecified;
        
        private decimal pMINField;
        
        private bool pMINFieldSpecified;
        
        private string wREField;
        
        private tPasmoPozycjiGrafiku[] bField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        public decimal PMAX {
            get {
                return this.pMAXField;
            }
            set {
                this.pMAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PMAXSpecified {
            get {
                return this.pMAXFieldSpecified;
            }
            set {
                this.pMAXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PMIN {
            get {
                return this.pMINField;
            }
            set {
                this.pMINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PMINSpecified {
            get {
                return this.pMINFieldSpecified;
            }
            set {
                this.pMINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string WRE {
            get {
                return this.wREField;
            }
            set {
                this.wREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("B")]
        public tPasmoPozycjiGrafiku[] B {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tOkresZgloszenia {
        
        private tOkres dtField;
        
        private string rField;
        
        private tDaneIloscioweZgloszenia[] tField;
        
        public tOkresZgloszenia() {
            this.rField = "PT15M";
        }
        
        /// <remarks/>
        public tOkres DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public string R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T")]
        public tDaneIloscioweZgloszenia[] T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tOkres {
        
        private System.DateTime dTSField;
        
        private System.DateTime dTKField;
        
        /// <remarks/>
        public System.DateTime DTS {
            get {
                return this.dTSField;
            }
            set {
                this.dTSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DTK {
            get {
                return this.dTKField;
            }
            set {
                this.dTKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tGrafikZOEB {
        
        private string mRIDField;
        
        private tTypGrafiku ptField;
        
        private tKierunek dField;
        
        private bool dFieldSpecified;
        
        private string kWSField;
        
        private string kJBField;
        
        private tOkresZgloszenia tSPField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public tTypGrafiku PT {
            get {
                return this.ptField;
            }
            set {
                this.ptField = value;
            }
        }
        
        /// <remarks/>
        public tKierunek D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DSpecified {
            get {
                return this.dFieldSpecified;
            }
            set {
                this.dFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string KWS {
            get {
                return this.kWSField;
            }
            set {
                this.kWSField = value;
            }
        }
        
        /// <remarks/>
        public string KJB {
            get {
                return this.kJBField;
            }
            set {
                this.kJBField = value;
            }
        }
        
        /// <remarks/>
        public tOkresZgloszenia TSP {
            get {
                return this.tSPField;
            }
            set {
                this.tSPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public enum tTypGrafiku {
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        PO,
        
        /// <remarks/>
        WL,
        
        /// <remarks/>
        WJB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public enum tKierunek {
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tZOEB {
        
        private string mRIDField;
        
        private string wField;
        
        private string kJGField;
        
        private string koField;
        
        private string kDUBField;
        
        private string iDOTField;
        
        private tOkres dtField;
        
        private tGrafikZOEB[] tsField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string W {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        /// <remarks/>
        public string KJG {
            get {
                return this.kJGField;
            }
            set {
                this.kJGField = value;
            }
        }
        
        /// <remarks/>
        public string KO {
            get {
                return this.koField;
            }
            set {
                this.koField = value;
            }
        }
        
        /// <remarks/>
        public string KDUB {
            get {
                return this.kDUBField;
            }
            set {
                this.kDUBField = value;
            }
        }
        
        /// <remarks/>
        public string IDOT {
            get {
                return this.iDOTField;
            }
            set {
                this.iDOTField = value;
            }
        }
        
        /// <remarks/>
        public tOkres DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TS")]
        public tGrafikZOEB[] TS {
            get {
                return this.tsField;
            }
            set {
                this.tsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tTresc {
        
        private tZOEB oEBField;
        
        /// <remarks/>
        public tZOEB OEB {
            get {
                return this.oEBField;
            }
            set {
                this.oEBField = value;
            }
        }
    }
}
