//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace xmlObjectProvider.Objects.ZOPMB {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.pse.pl/osp")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.pse.pl/osp", IsNullable=false)]
    public partial class Komunikat {
        
        private Naglowek naglowekField;
        
        private tTresc trescField;
        
        /// <remarks/>
        public Naglowek Naglowek {
            get {
                return this.naglowekField;
            }
            set {
                this.naglowekField = value;
            }
        }
        
        /// <remarks/>
        public tTresc Tresc {
            get {
                return this.trescField;
            }
            set {
                this.trescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class Naglowek {
        
        private string kod_komField;
        
        private System.DateTime dataField;
        
        private string kod_obiektuField;
        
        private System.DateTime data_utworzeniaField;
        
        private string wersjaField;
        
        private string idField;
        
        private string ref_idField;
        
        /// <remarks/>
        public string kod_kom {
            get {
                return this.kod_komField;
            }
            set {
                this.kod_komField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string kod_obiektu {
            get {
                return this.kod_obiektuField;
            }
            set {
                this.kod_obiektuField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data_utworzenia {
            get {
                return this.data_utworzeniaField;
            }
            set {
                this.data_utworzeniaField = value;
            }
        }
        
        /// <remarks/>
        public string wersja {
            get {
                return this.wersjaField;
            }
            set {
                this.wersjaField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ref_id {
            get {
                return this.ref_idField;
            }
            set {
                this.ref_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tDaneIlosciowe {
        
        private string pField;
        
        private string pOMField;
        
        private decimal cOMField;
        
        private bool cOMFieldSpecified;
        
        private decimal cOMRRField;
        
        private bool cOMRRFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string POM {
            get {
                return this.pOMField;
            }
            set {
                this.pOMField = value;
            }
        }
        
        /// <remarks/>
        public decimal COM {
            get {
                return this.cOMField;
            }
            set {
                this.cOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COMSpecified {
            get {
                return this.cOMFieldSpecified;
            }
            set {
                this.cOMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal COMRR {
            get {
                return this.cOMRRField;
            }
            set {
                this.cOMRRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COMRRSpecified {
            get {
                return this.cOMRRFieldSpecified;
            }
            set {
                this.cOMRRFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tOkresZgloszenia {
        
        private tOkres dtField;
        
        private string rField;
        
        private tDaneIlosciowe[] tField;
        
        public tOkresZgloszenia() {
            this.rField = "PT60M";
        }
        
        /// <remarks/>
        public tOkres DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        public string R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T")]
        public tDaneIlosciowe[] T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tOkres {
        
        private System.DateTime dTSField;
        
        private System.DateTime dTKField;
        
        /// <remarks/>
        public System.DateTime DTS {
            get {
                return this.dTSField;
            }
            set {
                this.dTSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DTK {
            get {
                return this.dTKField;
            }
            set {
                this.dTKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tGrafikZOPMB {
        
        private string mRIDField;
        
        private tMocyBilansujacej btField;
        
        private tOkresZgloszenia tSPField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        public tMocyBilansujacej BT {
            get {
                return this.btField;
            }
            set {
                this.btField = value;
            }
        }
        
        /// <remarks/>
        public tOkresZgloszenia TSP {
            get {
                return this.tSPField;
            }
            set {
                this.tSPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public enum tMocyBilansujacej {
        
        /// <remarks/>
        FCR_G,
        
        /// <remarks/>
        FCR_D,
        
        /// <remarks/>
        aFRR_G,
        
        /// <remarks/>
        aFRR_D,
        
        /// <remarks/>
        mFRRd_G,
        
        /// <remarks/>
        mFRRd_D,
        
        /// <remarks/>
        RR_G,
        
        /// <remarks/>
        RR_D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tOfertaZOPMB {
        
        private string bnField;
        
        private tGrafikZOPMB[] tsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BN {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TS")]
        public tGrafikZOPMB[] TS {
            get {
                return this.tsField;
            }
            set {
                this.tsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tZOPMB {
        
        private string mRIDField;
        
        private string wField;
        
        private string kDUBField;
        
        private string koField;
        
        private string iDOTField;
        
        private tOkres dtField;
        
        private tOfertaZOPMB[] bIDField;
        
        /// <remarks/>
        public string mRID {
            get {
                return this.mRIDField;
            }
            set {
                this.mRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string W {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        /// <remarks/>
        public string KDUB {
            get {
                return this.kDUBField;
            }
            set {
                this.kDUBField = value;
            }
        }
        
        /// <remarks/>
        public string KO {
            get {
                return this.koField;
            }
            set {
                this.koField = value;
            }
        }
        
        /// <remarks/>
        public string IDOT {
            get {
                return this.iDOTField;
            }
            set {
                this.iDOTField = value;
            }
        }
        
        /// <remarks/>
        public tOkres DT {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BID")]
        public tOfertaZOPMB[] BID {
            get {
                return this.bIDField;
            }
            set {
                this.bIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pse.pl/osp")]
    public partial class tTresc {
        
        private tZOPMB oPMBField;
        
        /// <remarks/>
        public tZOPMB OPMB {
            get {
                return this.oPMBField;
            }
            set {
                this.oPMBField = value;
            }
        }
    }
}
